updated vcut to error if not given enough arguments

diff --git a/src/vcut b/src/vcut
--- a/src/vcut
+++ b/src/vcut
@@ -148,6 +148,12 @@ parse_args() {
         esac
         shift
     done
+
+    if [ -z "${src}" -o -z "${dst}" ]; then
+        echo "vcut: missing arguments" >&2
+        echo "usage: vcut <src> <dst> [--debug]" >&2
+        return 1
+    fi
 }
 
 main() {
